### PR TITLE
Strings conversion refactoring

### PR DESCRIPTION
**Pull request by mlocati**
Let's centralize the string conversions.

I also found another problem when decoding PO strings (see failing test):
```po
msgid "Newline\nSlash and n\\nend"
```

Should be decoded as
```
Newline
Slash and n\nend
```

But is decoded as
```
Newline
Slash and n
end
```

### CODE REVIEW

**Comment by mlocati** [comment]
I updated this pull request, fixing the [current `\\` related problem](https://travis-ci.org/oscarotero/Gettext/builds/109804787) and implementing what's described in #95

**Comment by oscarotero** [comment]
Why not put each string function inside the class that use it? I mean:

```php
Extractors\Po::convertString($string);
Extractors\PhpCode::convertString($string);
Generators\Po::convertString($string);

//instead of
String::fromPo($string);
String::fromPhp($string);
String::toPo($string);
```
So we can improve other extractors (like jsCode, for example) without need to modify other helpers classes.

**Comment by mlocati** [comment]
Yes, good idea

**Comment by mlocati** [comment]
Done.

**Comment by oscarotero** [comment]
Great. Thank you. Can this be merged?

**Comment by mlocati** [comment]
Sure!

**Comment by oscarotero** [comment]
:+1:

**Pull request merged**
