### PR TITLE
Improve tests

### PR DESCRIPTION
**Pull request by mlocati**
I'm going to add some more test to this pull request.

Let's start by simplifying the current tests by using a common bootstrap file.

### CODE REVIEW

**Comment by mlocati** [comment]
[Added a fix](https://github.com/mlocati/Gettext/commit/ef8bbfea9c6967189769c8a9facbd697c4ea26f0) because getPluralForms wasn't working (see http://3v4l.org/2d41L )

**Comment by mlocati** [comment]
https://github.com/oscarotero/Gettext/commit/c6e2dd5031f03d20f83583eb004d15930d1fc3eb: because Translation instances had already the pluralTranslation array initialized to the correct size and new values were appended to them, giving longer pluralTranslation

**Comment by mlocati** [comment]
https://github.com/oscarotero/Gettext/commit/5d5952aead161a95808ff21c649eb6fed2e23ccf check if a cloned `Translations` actually clones its `Translation`s, and it seems that it doesn't...

**Comment by mlocati** [comment]
https://github.com/mlocati/Gettext/commit/3c294c59731fc44ce90e9e51824a07007ccc2588: fixed typo

**Comment by mlocati** [comment]
Plurals handling seems really good! :wink:

**Comment by mlocati** [comment]
I guess version 3.0 is coming soon :wink:

**Comment by mlocati** [comment]
I'm done with this PR

**Comment by oscarotero** [comment]
I hope to release the 3.0 version today or tomorrow. I want to check it before but I have to find time

**Pull request merged**
