### PR TITLE
fix plural forms validation

### PR DESCRIPTION
**Pull request by soukicz**
My previous PR https://github.com/oscarotero/Gettext/pull/156 missed some characters in plural forms validation

### CODE REVIEW

**Comment by oscarotero** [comment]
Maybe an easier solution is just check whether the plural form has any letter different than `n`?
Somethin like this (not tested):
```php
if (preg_match('/[A-Ma-mO-Zo-z]/', str_replace('return ', '', $code)) {
    throw new \InvalidArgumentException('Invalid Plural form: ' . $code);
}
```
Just an idea, what do you think?

**Comment by soukicz** [comment]
It would be also better to check it in setter before variable substitution. I will updated it.

**Comment by oscarotero** [comment]
We can also test the regexp with all possible formulas to be sure that doesn't fail with any valid plural formula.

```php
$languages = Gettext\Languages\Language::getAll();

foreach ($languages as $language) {
    //test $language->formula
}
```

**Comment by soukicz** [comment]
I have simplified validation and added testing for predefined plural forms.

**Comment by oscarotero** [comment]
Great. Thank you 👍

**Pull request merged**
