### PR TITLE
add fix to skip ' with trailing slash

### PR DESCRIPTION
**Pull request by AleksSem**
add fix to skip ' with trailing slash in translation for example {i18n.__('You don\'t have any bookmark.')}

### CODE REVIEW

**Comment by mlocati** [comment]
What if we have an even number of `\` before `'`?

**Comment by AleksSem** [comment]
I don`t check that issue with multiple \ but without that fix ill get 

You don'thaveanybookmark.')}</h5> <p>{i18n.__('Youcanadda .....................

instead {i18n.__('You don't have any bookmark.')}

**Comment by AleksSem** [comment]
Yes you definitely right, your solution i better.

**Comment by AleksSem** [comment]
Should work now

**Comment by oscarotero** [comment]
Thanks 👍

**Pull request merged**
