### PR TITLE
don't check Po file content on bigendian

### PR DESCRIPTION
**Pull request by remicollet**
As all Po reference files are LittleEndian

### CODE REVIEW

**Comment by bowlofeggs** [comment]
+1

**Comment by oscarotero** [comment]
Could this fixed using a function like this? http://shiplu.mokadd.im/95/convert-little-endian-to-big-endian-in-php-or-vice-versa/
If so, there's no need to skip tests.

**Comment by remicollet** [comment]
The problem is about reference files provided in the tests/assert directory.

If you don't want to skip this tests, you have to provide both versions (little and big endian)

**Comment by oscarotero** [comment]
Sorry, I don't understand. I've no experience with little/big endian.
What I mean is to convert the string from little-endian to big-endian before the assertion, using the function linked above. If this does not solve the problem, I can merge it anyway, but I'd preffer not to skip tests if it's possible.

**Comment by remicollet** [comment]
```
$ file tests/assets/po/Mo.mo
tests/assets/po/Mo.mo: GNU message catalog (little endian), revision 0.0, 4 messages
```

So you cannot compare file generated by the library (which will be Big Endian), and reference file which is Little Endian.

**Comment by bowlofeggs** [comment]
Thanks!

**Pull request merged**
