### PR TITLE
Mo genetation stuff reloaded

### PR DESCRIPTION
**Pull request by mlocati**
Previous PR wasn't still ready. And so is this one: please wait, don't merge it.

This PR fixes the generation of PO files.
There's still another problem: reading mo files doesn't parse the headers. I'll keep updated this PR and tell you when it's ready (you'll see that TravisCI integrated tests will give you a go :wink: )

### CODE REVIEW

**Comment by mlocati** [comment]
PS: this new .mo generation code comes [from myself](https://github.com/mlocati/concrete5-localizer/blob/master/helpers/translation_file.php)

**Comment by mlocati** [comment]
Ok, all seems to be fine, now :wink:

**Comment by oscarotero** [comment]
Right. I'll have a look to all these changes and create a new release with it.
Thank you, I appreciate your work

**Comment by mlocati** [comment]
> [...] and create a new release with it.

:+1:

**Pull request merged**
