### PR TITLE
Update Po.php

### PR DESCRIPTION
**Pull request by Krato**
Function to Escape Control Characters like EOT from strings.

### CODE REVIEW

**Comment by oscarotero** [comment]
Thank you :+1:

**Comment by Krato** [comment]
No problem! ;)

**Comment by mlocati** [comment]
I think we have a problem here: the control chars are not escaped, they are simply removed...

**Comment by mlocati** [comment]
@Krato The recent changes to this repository will keep the bytes that you call "Control Characters like EOT"
That's because we can't strip out the bytes in the ranges `\x01-\x09`, `\x0B`, `\x0C`, `\x0E-\x1F`, `x7F` since they may be used in multibyte strings

**Pull request merged**
