### PR TITLE
Trim tab characters from comment lines

### PR DESCRIPTION
**Pull request by ocean90**
Related report: https://github.com/wp-cli/i18n-command/issues/169

When a PHP comment is indented with a tab character it currently doesn't get extracted. Adding the tab to the characters to strip will fix this.

### CODE REVIEW

**Comment by swissspidy** [comment]
Looks like this breaks `Gettext\Tests\AssetsTest::testTwig
twig/Po` as the line numbers change. Haven't checked whether the assertions were actually wrong or if this is a regression.

**Comment by ocean90** [comment]
@swissspidy Those are unrelated based on the build status of the master branch.

**Comment by swissspidy** [comment]
Ah yes, indeed! 👍

**Comment by ocean90** [comment]
https://github.com/oscarotero/Gettext/pull/216 updates the incorrect line numbers.

**Comment by oscarotero** [comment]
Thanks 👍

**Pull request merged**
