### PR TITLE
Fix mo generation

### PR DESCRIPTION
**Pull request by mlocati**
Sorry, I did a little mistake... This fixes it.

### CODE REVIEW

**Comment by mlocati** [comment]
:ok:

**Comment by mlocati** [comment]
The problem here is that I'm not sure if a translatable string is identified by context+original or by context+original+plural.
This PR adopts the second approach, that's compatible with what we had before all those PRs of mine :wink:

**Comment by oscarotero** [comment]
I guess the second approach is the right one, but I'm not sure. :+1:

**Comment by mlocati** [comment]
> I guess the second approach is the right one, but I'm not sure. 

Me too. From the [gettext docs](http://www.gnu.org/software/gettext/manual/gettext.html#MO-Files) we have:
> only the singular of the original string takes part in the hash table lookup

We may think from that sentence that we can't have two strings with the same context+original, even if one is singular and the others have plurals... But since we don't use the hash table let's skip this (rare) argument :wink:

**Pull request merged**
