### PR TITLE
Test multibyte and tab chars

### PR DESCRIPTION
**Pull request by mlocati**
This will fail...

### CODE REVIEW

**Comment by mlocati** [comment]
...but the next commit should fix this problem :wink:

**Comment by oscarotero** [comment]
Good job. Thank you very much!

**Comment by mlocati** [comment]
I still have to review the po loader, since there too we should be sure to correctly parse the input strings... Tomorrow I will

**Comment by oscarotero** [comment]
:+1:

**Comment by mlocati** [comment]
PS: I just performed the following test on 50+ languages, each with 4000+ strings (including languages that make great use of multibyte chars like Arabic, Greek, Hebrew, Japanese, Persian, Russian, Simplified Chinese, Traditional Chinese, Vietnamese...)

1. Load .po file generated with GNU gettext tools
2. Save to a new .po file
3. compare both files with `msgcat -u` to look for differences between the two

Result? No difference has been found.

That means that `oscarotero/Gettext` correctly reads and writes .po files :wink:

**Comment by oscarotero** [comment]
Amazing :dancers:

**Pull request merged**
